config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :soccer_courts
  resources :rols
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'home#index'

  get "/reservations/getreservations/get", :to => 'reservations#getreservations'
  get "/reservations/getreservations/getMisReservas", :to => 'reservations#getMisReservas'
  get "/reservations/getreservations/cancelReservation", :to => 'reservations#cancelReservation'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :soccer_court
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroys]
  before_action :authenticate_user!, except: [:getreservations]
  
  before_action :authenticate_admin!, only: [:destroy]
  layout "reservas"




  # GET /reservations
  # GET /reservations.json
  # Retornar las vista index junto con todos los registros de las reservas
  def index
    @reservations = Reservation.all
    # @test= SoccerCourt.includes(:reservation).find(params[:soccer_court_id])
    byebug
     @soccer_court_id= params[:soccer_court_id]
  end

  # GET /reservations/getReservations/get
  # Retorna las reservas pertenecientes a una cancha y fecha especificadas
  def getreservations
    byebug
    soccer_court_id= params[:id].to_i
    date=params[:date]
    byebug
    @reservations= Reservation.where(soccer_court_id: soccer_court_id, isActive: true, dateOfReservation: date)
    render json: @reservations
  end

  # POST /reservations/getReservations/misReservas
  # Retorna la vista de las reservas activas de un usuario
  def getMisReservas

    test =  SoccerCourt.joins(:reservation).where(reservations: {user_id: 1,isActive: true}).select('*');
    @reservationsOfUser =test    
    render "MisReservas"       
  end

  # GET /reservations/reservation_id
  # Cambia el estatus de la reserva a cancelado
  def cancelReservation
  
    id = params[:id]    
    reservation = Reservation.find_by(id: id)
    reservation.isActive = false;
    reservation.save

    test =  SoccerCourt.joins(:reservation).where(reservations: {user_id: 1,isActive: true}).select('*');
    @reservationsOfUser =test
    render "MisReservas"
  end


  # GET /reservations/1
  # GET /reservations/1.json
  # Retorna la vista show
  def show
  end

  # GET /reservations/new
  # Muestra la vista para registrar una reserva
  def new
    @reservation = Reservation.new
    @soccer_court_id = params[:id]
    date=params[:date]
    
    @reservations= Reservation.where(soccer_court_id: @soccer_court_id, isActive: true, dateOfReservation: date)
   
  end

  # GET /reservations/1/edit
  # Retorna la vista de edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  # Registra una nueva reserva y envia un correo
  # de notificacion al usuario
  def create
    @reservation = Reservation.new(reservation_params)
    
    # @reservation.timeOfReservation=@reservation.timeOfReservation.strftime('%H')
    byebug
    respond_to do |format|
      if @reservation.save
        @reservation= Reservation.last
        #Envio de correo , registro exitoso
        NotifyMailer.send_mail(current_user.email,'Registro de reserva',@reservation).deliver
        
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  # Actualiza una reserva
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  # Elinima una reserva
  def destroy
    
    respond_to do |format|
      @reservation.isActive = false;
      @reservation.update(@reservation);
      format.html { redirect_to reservations_url, notice: 'La reserva se cancelo correctamente' }
      format.json { head :no_content }
    end
  end

  private
    # Usa los callbacks para compartir la configuración común o las restricciones entre las acciones.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Especifica los parametros permitidos en las peticiones
    def reservation_params
      params.require(:reservation).permit(:dateOfReservation, :timeOfReservation, :isActive, :price, :user_id, :soccer_court_id, :date)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/MisReservas.html.erb
<div class="container" style="margin-top:5em; margin-bottom:4em;">
     <h1 style="margin-bottom:2em; text-align: center">Mis Reservas</h1>

    <div class="row">

    <% @reservationsOfUser.each do |reservation| %>
    <div class="col-lg-3 col-xs-12">
        <div class="list-group">
        <div  class="list-group-item ">
            <h3 class="list-group-item-heading"><%= reservation.name%></h3>
            <p class="list-group-item-text">Reservado para el dia <%= reservation.dateOfReservation%> a las <%= reservation.timeOfReservation%></p>
            <br />            
            <a href="/reservations/getreservations/cancelReservation?id=<%= reservation.id%>" class="btn btn-danger" role="button">cancel</a>            
        </div>
        </div>
     </div>
    <% end %>
    


    </div>


</div>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br />
  <br />
  <br />
  <div class="field" style="display:none">
    <label>Usuario</label>
    <input type="Text" name="reservation[user_id]" value="<%= current_user.id%>" />
  </div>

  <div class="field" style="display:none">
    <label>soccer_court_id</label>
    <input type="Text" name="reservation[soccer_court_id]" value="<%= @soccer_court_id %>" />
  </div>

  <div class="field">
    <%= form.label :dateOfReservation %>
    <%= form.date_select :dateOfReservation, id: :reservation_dateOfReservation, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :timeOfReservation %>
    <%= form.time_select :timeOfReservation, { :discard_minute => true, id: :reservation_timeOfReservation } %>
  </div>

  <div class="field">
    <%= form.label :isActive %>
    <%= form.check_box :isActive, id: :reservation_isActive %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price,id: :reservation_price, class: "form-control", style: "width:300px;" %>
  </div>

  <div class="actions" style="margin-top:2em;" >
    <%= form.submit 'Guardar', :class => 'btn btn-lg btn-success'  %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

    <!--Full calendar-->
    <link rel='stylesheet' href='/fullcalendar/fullcalendar.css' />
    <script src='/fullcalendar/lib/jquery.min.js'></script>
    <script src='/fullcalendar/lib/moment.min.js'></script>
    <script src='/fullcalendar/fullcalendar.js'></script>
    <script src='/fullcalendar/lib/jquery-ui.min.js'></script>
    <script src='/fullcalendar/locale/es.js'></script>

    <script src="/JS/Reservations/index.js"></script>

<style>
body {
  margin: 0;
  padding: 0;
  font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
  font-size: 14px;
}
#calendar {
  max-width: 900px;
  margin: 40px auto;
  padding: 0 10px;
}


</style>

<div style="display: <%= (user_signed_in? && current_user.is_admin?) ? 'none' : 'block' %> ">
<div class="container" >
  <h1 style="text-align:center">Reservas</h1>

  <div class="row" >
  <%= link_to "Mis Reservas", { controller: "reservations", action: "getMisReservas" }, class: "btn btn-lg btn-info", style: "margin-left:7em;" %>
  </div>
</div>
<div class="row">
<div id='calendar'></div>
</div>
</div>


<div style="display: <%= (user_signed_in? && !current_user.is_admin?) ? 'none' : 'block' %> ">
<h1>Reservations</h1>

<table class="table table-responsive table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>Dateofreservation</th>
      <th>Timeofreservation</th>
      <th>Isactive</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.dateOfReservation %></td>
        <td><%= reservation.timeOfReservation %></td>
        <td><%= reservation.isActive %></td>
        <td><%= reservation.price %></td>
        <td><%= link_to 'Ver', reservation,class: "btn btn-default" %></td>
        <td><%= link_to 'Editar', edit_reservation_path(reservation),class: "btn btn-info" %></td>
        <!--<td><%= link_to 'Cancelar', reservation, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path, class: "btn btn-success" %>

</div>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dateofreservation:</strong>
  <%= @reservation.dateOfReservation %>
</p>

<p>
  <strong>Timeofreservation:</strong>
  <%= @reservation.timeOfReservation %>
</p>

<p>
  <strong>Isactive:</strong>
  <%= @reservation.isActive %>
</p>

<p>
  <strong>Price:</strong>
  <%= @reservation.price %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>