config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :soccer_courts
  resources :rols
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'home#index'

  get "/reservations/getreservations/get", :to => 'reservations#getreservations'
  get "/reservations/getreservations/getMisReservas", :to => 'reservations#getMisReservas'
  get "/reservations/getreservations/cancelReservation", :to => 'reservations#cancelReservation'
end

app/models/soccer_court.rb
class SoccerCourt < ApplicationRecord
    has_many :reservation
end

app/controllers/soccer_courts_controller.rb
class SoccerCourtsController < ApplicationController
  before_action :set_soccer_court, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authenticate_admin!, only: [:destroy]
  layout "reservas"
  # GET /soccer_courts
  # GET /soccer_courts.json
  # Retorna la vista de index junto con el listado de Canchas
  def index
    @soccer_courts = SoccerCourt.all
  end

  # GET /soccer_courts/1
  # GET /soccer_courts/1.json
  # Retorna la vista Show
  def show
  end

  # GET /soccer_courts/new
  # Retorna la vista de new para crear una nueva cancha
  def new
    @soccer_court = SoccerCourt.new
  end

  # GET /soccer_courts/1/edit
  # Retorna la vista edit para editar una cancha
  def edit
  end

  # POST /soccer_courts
  # POST /soccer_courts.json
  # Crea una cancha
  def create
    @soccer_court = SoccerCourt.new(soccer_court_params)

    respond_to do |format|
      if @soccer_court.save
        format.html { redirect_to @soccer_court, notice: 'Soccer court was successfully created.' }
        format.json { render :show, status: :created, location: @soccer_court }
      else
        format.html { render :new }
        format.json { render json: @soccer_court.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /soccer_courts/1
  # PATCH/PUT /soccer_courts/1.json
  # Actualiza una cancha
  def update
    respond_to do |format|
      if @soccer_court.update(soccer_court_params)
        format.html { redirect_to @soccer_court, notice: 'Soccer court was successfully updated.' }
        format.json { render :show, status: :ok, location: @soccer_court }
      else
        format.html { render :edit }
        format.json { render json: @soccer_court.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /soccer_courts/1
  # DELETE /soccer_courts/1.json
  # Borra una cancha
  def destroy
    @soccer_court.destroy
    respond_to do |format|
      format.html { redirect_to soccer_courts_url, notice: 'Soccer court was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Retornar las vista index junto con todos los registros de las reservas
    def set_soccer_court
      @soccer_court = SoccerCourt.find(params[:id])
    end

    # Especifica los parametros permitidos en las peticiones
    def soccer_court_params
      params.require(:soccer_court).permit(:name, :location, :price, :isActive)
    end
end

app/helpers/soccer_courts_helper.rb
module SoccerCourtsHelper
end

app/views/soccer_courts/_form.html.erb
<%= form_with(model: soccer_court, local: true) do |form| %>
  <% if soccer_court.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(soccer_court.errors.count, "error") %> prohibited this soccer_court from being saved:</h2>

      <ul>
      <% soccer_court.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :soccer_court_name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :soccer_court_location %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :soccer_court_price %>
  </div>

  <div class="field">
    <%= form.label :isActive %>
    <%= form.check_box :isActive, id: :soccer_court_isActive %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/soccer_courts/edit.html.erb
<h1>Editing Soccer Court</h1>

<%= render 'form', soccer_court: @soccer_court %>

<%= link_to 'Show', @soccer_court %> |
<%= link_to 'Back', soccer_courts_path %>

app/views/soccer_courts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Soccer Courts</h1>


<br>
<div style="display: <%= (user_signed_in? && !current_user.is_admin?) ? 'none' : 'block' %> ">
<%= link_to 'New Soccer Court', new_soccer_court_path,class: "btn btn-success" %>
</div>
<div class="row">
<% @soccer_courts.each do |soccer_court| %>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="/images/cancha2.png" alt="...">
      <div class="caption">
        <h3><%= soccer_court.name %></h3>
        <strong>Localizacion</strong>
        <p><%= soccer_court.location %></p>
        <strong style="display:inline">Precio </strong><p style="display:inline"><%= soccer_court.price %></p>
        <br/>
        <hr/>
        <p><a href="/reservations?soccer_court_id=<%= soccer_court.id%>" class="btn btn-primary" role="button">Reservar</a></p>
      </div>
    </div>
  </div>

<% end %>
</div>

app/views/soccer_courts/new.html.erb
<h1>New Soccer Court</h1>

<%= render 'form', soccer_court: @soccer_court %>

<%= link_to 'Back', soccer_courts_path %>

app/views/soccer_courts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @soccer_court.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @soccer_court.location %>
</p>

<p>
  <strong>Price:</strong>
  <%= @soccer_court.price %>
</p>

<p>
  <strong>Isactive:</strong>
  <%= @soccer_court.isActive %>
</p>

<%= link_to 'Edit', edit_soccer_court_path(@soccer_court) %> |
<%= link_to 'Back', soccer_courts_path %>